
//FOLDERS
var THEMESFOLDERNAME="THEMES";
var GALLERIESFOLDERNAME="i5GALLERIES";


//FILES
var i5UIOBJECTSMETAFILENAME="i5uiobjectsmeta.js";
var THEMESFILENAME="i5thememanifest.js";


//UI OBJECTS
var THISi5APPUIOBJECTS;
var SELECTEDAPPUIOBJECT;
var SELECTEDAPPUIOBJECTS;

//CONTENT OBJECTS
var THISi5APPCONTENTOBJECTS;

//DRAWING SURFACE VARIABLES
var ARRAYOFDRAWINGSURFACES=new Array();

var i5DEBUG=true;


var MAINPRESENTATIONWINDOW;
var MAINMENUBAR;
var MAINTOOLBAR;


//WINDOW VARIABLES
var ARRAYOFWINDOWS=new Array();
var PADDINGBETWEENWINDOWS=20;
var AVAILABLELEFT=0;
var AVAILABLETOP=0;
var AVAILABLERIGHT=window.innerWidth  - window.PADDINGBETWEENWINDOWS;
var AVAILABLEBOTTOM=window.innerHeight - window.PADDINGBETWEENWINDOWS;

//GALLERY VARIABLES
var ARRAYOFGALLERIES=new Array();
var ARRAYOFDRAWINGSURFACES=new Array();
var ARRAYOFSCRIPTS=new Array();

//ZINDEX
var MAXZINDEX=0;
var MINZINDEX=0;


//CSS3 PROPERTIES
BOXSHADOWPROPERTYARRAY=["boxShadow","MozBoxShadow","WebKitBoxShadow"];
BORDERRADIUSPROPERTYARRAY=["borderRadius","MozBorderRadius","WebKitBorderRadius"];


//GALLERY OBJECTS
var i5GALLERYUIOBJECTS;
var i5GALLERYMANAGER;

//EFFECTS
var SHADOWEFFECT;

//PRESENTATION OBJECTS
var SELECTEDOBJECT;
var SELECTEDOBJECTS=new Array();
var SHAPEOBJECT;
